[package]
name = "tycho-wallet-api"
version = "1.0.0"
edition = "2021"
authors = ["Broxus team"]
publish = false
license-file = "LICENSE"

[dependencies]
aide = { version = "0.13.5", features = ["axum", "axum-extra", "scalar", "macros"] }
anyhow = "1.0"
axum = { version = "0.7", features = ["multipart", "macros"] }
argon2 = "0.4.1"
async-trait = "0.1"
base64 = "0.13"
bigdecimal = { version = "0.4.5", features = ["serde"] }
chacha20poly1305 = "0.10.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.3", features = ["derive"] }
dashmap = "5.3.4"
derive_more = { version = "1.0.0", features = ["full"] }
futures = "0.3"
futures-util = "0.3.31"
hex = "0.4"
hmac-sha256 = "1.1.4"
http = "0.2"
itertools = "0.10.1"
lazy_static = "1.4.0"
log = { version = "0.4", features = ["std", "serde"] }
lru = "0.8"
metrics = "0.20.1"
metrics-exporter-prometheus = { version = "0.16.0", default-features = false, features = ["http-listener"] }
num-bigint = "0.4"
num-traits = "0.2"
opg = { version = "0.2", features = ["uuid"] }
parking_lot = "0.12.0"
pomfrit = "0.1"
rand = "0.8"
rayon = "1.10"
regex = "1.5"
reqwest = { version = "0.12", features = ["json"] }
rustc-hash = "1.1.0"
schemars = { version = "0.8.13", features = ["chrono", "bigdecimal04", "uuid1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.4"
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "postgres", "uuid", "bigdecimal", "chrono", "json"] }
strum = "0.24.1"
strum_macros = "0.24.1"
thiserror = "1.0"
tokio = { version = "1", features = ["sync", "fs", "rt-multi-thread", "macros", "signal", "parking_lot"] }
tokio-util = "0.7"
tower = { version = "0.5", features = ["limit"] }
tower-http = { version = "0.6", features = ["trace", "cors", "limit", "set-header", "metrics"] }
tower-service = "0.3.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tycho-types = { version = "0.3.0", features = ["tycho", "stats"] }

uuid = { version = "1.1", features = ["v4", "serde"] }

ed25519-dalek = { git = "https://github.com/broxus/ed25519-dalek.git" }

tikv-jemallocator = { version = "0.6.0", features = [
    "unprefixed_malloc_on_supported_platforms",
    "background_threads",
] }

tycho-block-util = { git = "https://github.com/broxus/tycho.git", rev = "7cb68c97c1109c8412e35fda1db6bd3a870421fa" }
tycho-core = { git = "https://github.com/broxus/tycho.git", rev = "7cb68c97c1109c8412e35fda1db6bd3a870421fa" }
tycho-light-node = { git = "https://github.com/broxus/tycho.git", rev = "7cb68c97c1109c8412e35fda1db6bd3a870421fa" }
tycho-storage = { git = "https://github.com/broxus/tycho.git", rev = "7cb68c97c1109c8412e35fda1db6bd3a870421fa" }
tycho-util = { git = "https://github.com/broxus/tycho.git", rev = "7cb68c97c1109c8412e35fda1db6bd3a870421fa", features = ["cli"] }

tycho-vm = "0.3.0"
tycho-executor = "0.3.0"

# TON specific dependencies
ton_block = { git = "https://github.com/broxus/ton-labs-block" }
ton_abi = { git = "https://github.com/broxus/ton-labs-abi" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }

# Nekoton SDK
nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = true }
nekoton-abi = { git = "https://github.com/broxus/nekoton.git", features = ["derive"] }
nekoton-utils = { git = "https://github.com/broxus/nekoton.git" }
nekoton-contracts = { git = "https://github.com/broxus/nekoton.git" }

sysinfo = "0.30.13"

[features]
default = []
